export const FETCH_CATEGORIES_LIST_START = 'FETCH_CATEGORIES_LIST_START';
export const FETCH_CATEGORIES_LIST_FAILURE = 'FETCH_CATEGORIES_LIST_FAILURE';
export const FETCH_CATEGORIES_LIST_SUCCESS = 'FETCH_CATEGORIES_LIST_SUCCESS';

export const FETCH_CATEGORY_PROBLEMS_START = 'FETCH_CATEGORY_PROBLEMS_START';
export const FETCH_CATEGORY_PROBLEMS_FAILURE = 'FETCH_CATEGORY_PROBLEMS_FAILURE';
export const FETCH_CATEGORY_PROBLEMS_SUCCESS = 'FETCH_CATEGORY_PROBLEMS_SUCCESS';

export const ADD_PROBLEM_TO_SOLVED = 'ADD_PROBLEM_TO_SOLVED';

export const ADD_PROBLEM_TO_BASKET = 'ADD_PROBLEM_TO_BASKET';
export const REMOVE_PROBLEM_FROM_BASKET = 'REMOVE_PROBLEM_FROM_BASKET';
export const REORDER_PROBLEMS_IN_BASKET = 'REORDER_PROBLEMS_IN_BASKET';
