export const FETCH_CATEGORIES_LIST_START = 'FETCH_CATEGORIES_LIST_START';
export const FETCH_CATEGORIES_LIST_FAILURE = 'FETCH_CATEGORIES_LIST_FAILURE';
export const FETCH_CATEGORIES_LIST_SUCCESS = 'FETCH_CATEGORIES_LIST_SUCCESS';

export const FETCH_CATEGORY_PROBLEMS_START = 'FETCH_CATEGORY_PROBLEMS_START';
export const FETCH_CATEGORY_PROBLEMS_FAILURE = 'FETCH_CATEGORY_PROBLEMS_FAILURE';
export const FETCH_CATEGORY_PROBLEMS_SUCCESS = 'FETCH_CATEGORY_PROBLEMS_SUCCESS';

export const REODRED_CATEGORY_PROBLEMS_START = 'REODRED_CATEGORY_PROBLEMS_START';
export const REODRED_CATEGORY_PROBLEMS_FAILURE = 'REODRED_CATEGORY_PROBLEMS_FAILURE';
export const REODRED_CATEGORY_PROBLEMS_SUCCESS = 'REODRED_CATEGORY_PROBLEMS_SUCCESS';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const EDIT_CATEGORY_START = 'EDIT_CATEGORY_START';
export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';

export const POST_NEW_PROBLEM_START = 'POST_NEW_PROBLEM_START';
export const POST_NEW_PROBLEM_SUCCESS = 'POST_NEW_PROBLEM_SUCCESS';
export const POST_NEW_PROBLEM_FAILURE = 'POST_NEW_PROBLEM_FAILURE';

export const REMOVE_PROBLEM_START = 'REMOVE_PROBLEM_START';
export const REMOVE_PROBLEM_FAILURE = 'REMOVE_PROBLEM_FAILURE';
export const REMOVE_PROBLEM_SUCCESS = 'REMOVE_PROBLEM_SUCCESS';

export const EDIT_PROBLEM_START = 'EDIT_PROBLEM_START';
export const EDIT_PROBLEM_FAILURE = 'EDIT_PROBLEM_FAILURE';
export const EDIT_PROBLEM_SUCCESS = 'EDIT_PROBLEM_SUCCESS';

export const ADD_PROBLEM_TO_SOLVED = 'ADD_PROBLEM_TO_SOLVED';
export const REMOVE_PROBLEM_FROM_SOLVED = 'REMOVE_PROBLEM_FROM_SOLVED';

export const ADD_PROBLEM_TO_BASKET = 'ADD_PROBLEM_TO_BASKET';
export const REMOVE_PROBLEM_FROM_BASKET = 'REMOVE_PROBLEM_FROM_BASKET';
export const REORDER_PROBLEMS_IN_BASKET = 'REORDER_PROBLEMS_IN_BASKET';
export const CLEAR_BASKET = 'CLEAR_BASKET';

export const ADD_HOMEWORK_START = 'ADD_HOMEWORK_START';
export const ADD_HOMEWORK_FAILURE = 'ADD_HOMEWORK_FAILURE';
export const ADD_HOMEWORK_SUCCESS = 'ADD_HOMEWORK_SUCCESS';

export const FETCH_HOMEWORK_START = 'FETCH_HOMEWORK_START';
export const FETCH_HOMEWORK_FAILURE = 'FETCH_HOMEWORK_FAILURE';
export const FETCH_HOMEWORK_SUCCESS = 'FETCH_HOMEWORK_SUCCESS';

export const AUTH_START = 'AUTH_START';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const VERIFY_START = 'VERIFY_START';
export const VERIFY_FAILURE = 'VERIFY_FAILURE';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';

export const TOKEN = 'x-access-token';
